<a href="https://colab.research.google.com/github/nt189/Valores-nulos/blob/main/Actividad%203.2%20(Valores%20nulos)/Actividad_3_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
df = pd.read_csv('listings.csv')
df1 = df.copy()

In [17]:
nulos = df.isnull().sum()
nulos

name                                                1
description                                      1433
neighborhood_overview                           22421
host_name                                           2
host_location                                   10860
host_response_time                              10088
host_response_rate                              10088
host_acceptance_rate                             9683
host_is_superhost                                1252
host_neighbourhood                               9985
host_listings_count                                 2
host_total_listings_count                           2
host_verifications                                  2
host_identity_verified                              2
neighbourhood                                   22420
neighbourhood_cleansed                              0
neighbourhood_group_cleansed                        0
latitude                                            0
longitude                                           0
property_type                                       0
room_type                                           0
accommodates                                        0
bathrooms_text                                     25
bedrooms                                         3039
beds                                             8334
amenities                                           0
price                                            8237
minimum_nights                                      0
maximum_nights                                      0
has_availability                                 3339
availability_30                                     0
availability_60                                     0
availability_90                                     0
availability_365                                    0
number_of_reviews                                   0
number_of_reviews_ltm                               0
number_of_reviews_l30d                              0
first_review                                    12146
last_review                                     12146
review_scores_rating                            12146
review_scores_accuracy                          12155
review_scores_cleanliness                       12156
review_scores_checkin                           12163
review_scores_communication                     12156
review_scores_location                          12164
review_scores_value                             12165
instant_bookable                                    0
calculated_host_listings_count                      0
calculated_host_listings_count_entire_homes         0
calculated_host_listings_count_private_rooms        0
dtype: int64

In [18]:
#Sustituir valores nulos con promedio o media
df1['review_scores_rating'] = df1['review_scores_rating'].fillna(round(df['review_scores_rating'].mean(),1))
df1['review_scores_accuracy'] = df1['review_scores_accuracy'].fillna(round(df['review_scores_accuracy'].mean(),1))
df1['review_scores_cleanliness'] = df1['review_scores_cleanliness'].fillna(round(df['review_scores_cleanliness'].mean(),1))
df1['review_scores_checkin'] = df1['review_scores_checkin'].fillna(round(df['review_scores_checkin'].mean(),1))
df1['review_scores_communication'] = df1['review_scores_communication'].fillna(round(df['review_scores_communication'].mean(),1))
df1['review_scores_location'] = df1['review_scores_location'].fillna(round(df['review_scores_location'].mean(),1))
df1['review_scores_value'] = df1['review_scores_value'].fillna(round(df['review_scores_value'].mean(),1))

In [19]:
# Sustituir valores nulos con mediana
df1['host_response_rate'] = df1['host_response_rate'].fillna(round(df['host_response_rate'].median(),1))
df1['host_acceptance_rate'] = df1['host_acceptance_rate'].fillna(round(df['host_acceptance_rate'].median(),1))
df1['host_listings_count'] = df1['host_listings_count'].fillna(round(df['host_listings_count'].median(),1))
df1['host_total_listings_count'] = df1['host_total_listings_count'].fillna(round(df['host_total_listings_count'].median(),1))

In [20]:
# Susutitucion por un valor numerico en concreto
# df1['description'] = df1['description'].fillna()

In [39]:
# Sustituir valores nulos por un string en concreto
df1['description'] = df1['description'].fillna('Sin descripción')
df1['neighborhood_overview'] = df1['neighborhood_overview'].fillna('Sin descripción')
df1['host_is_superhost'] = df1['host_is_superhost'].fillna('f')
df1['host_location'] = df1['host_location'].fillna('f')
df1['has_availability'] = df1['has_availability'].fillna('t')
df1['first_review'] = df1['first_review'].fillna('Sin fecha')
df1['last_review'] = df1['last_review'].fillna('Sin fecha')

In [24]:
# sustituir valores nulos por valores no nulos hacia adelante 'forward fill' ('ffill')
df1['bathrooms_text'] = df1['bathrooms_text'].fillna(method = 'ffill')
df1['bedrooms'] = df1['bedrooms'].fillna(method = 'ffill')
df1['beds'] = df1['beds'].fillna(method = 'ffill')

<ipython-input-24-76c3247e3f81>:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1['bathrooms_text'] = df1['bathrooms_text'].fillna(method = 'ffill')
<ipython-input-24-76c3247e3f81>:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1['bedrooms'] = df1['bedrooms'].fillna(method = 'ffill')
<ipython-input-24-76c3247e3f81>:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1['beds'] = df1['beds'].fillna(method = 'ffill')

In [37]:
# Sustituir valores nulos por valores no nulos hacia atrás backward fill ("bfill")
df1['host_response_time'] = df1['host_response_time'].fillna(method = "bfill")
df1['host_neighbourhood'] = df1['host_neighbourhood'].fillna(method = "bfill")
df1['neighbourhood'] = df1['neighbourhood'].fillna(method = "bfill")
df1['host_verifications'] = df1['host_verifications'].fillna(method = "bfill")
df1['host_identity_verified'] = df1['host_identity_verified'].fillna(method = "bfill")

<ipython-input-37-c4cd0536c24e>:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1['host_response_time'] = df1['host_response_time'].fillna(method = "bfill")
<ipython-input-37-c4cd0536c24e>:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1['host_neighbourhood'] = df1['host_neighbourhood'].fillna(method = "bfill")
<ipython-input-37-c4cd0536c24e>:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1['neighbourhood'] = df1['neighbourhood'].fillna(method = "bfill")
<ipython-input-37-c4cd0536c24e>:5: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1['host_verifications'] = df1['host_verifications'].fillna(method = "bfill")
<ipython-input-37-c4cd0536c24e>:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1['host_identity_verified'] = df1['host_identity_verified'].fillna(method = "bfill")

In [43]:
nulos = df1.isnull().sum()
nulos

name                                            0
description                                     0
neighborhood_overview                           0
host_name                                       0
host_location                                   0
host_response_time                              0
host_response_rate                              0
host_acceptance_rate                            0
host_is_superhost                               0
host_neighbourhood                              0
host_listings_count                             0
host_total_listings_count                       0
host_verifications                              0
host_identity_verified                          0
neighbourhood                                   0
neighbourhood_cleansed                          0
neighbourhood_group_cleansed                    0
latitude                                        0
longitude                                       0
property_type                                   0
room_type                                       0
accommodates                                    0
bathrooms_text                                  0
bedrooms                                        0
beds                                            0
amenities                                       0
price                                           0
minimum_nights                                  0
maximum_nights                                  0
has_availability                                0
availability_30                                 0
availability_60                                 0
availability_90                                 0
availability_365                                0
number_of_reviews                               0
number_of_reviews_ltm                           0
number_of_reviews_l30d                          0
first_review                                    0
last_review                                     0
review_scores_rating                            0
review_scores_accuracy                          0
review_scores_cleanliness                       0
review_scores_checkin                           0
review_scores_communication                     0
review_scores_location                          0
review_scores_value                             0
instant_bookable                                0
calculated_host_listings_count                  0
calculated_host_listings_count_entire_homes     0
calculated_host_listings_count_private_rooms    0
dtype: int64

In [42]:
# Eliminamos filas con nulos
df1 = df1.dropna()

df1.to_csv('listings_limpio.csv', index=False)